FROM node:12-alpine

RUN set -ex; apk add --no-cache --virtual .fetch-deps curl git ;

WORKDIR /app

COPY base.package.json /app/package.json

RUN npm i

RUN chmod -R 777 /app

RUN rm -rf package.json